### ISSUE TITLE
Unable to deploy with UnicodeDecodeError

### ISSUE THREAD

**Issue by sanjeevkpandit** [kabirbaidhya/boss#135]
Command: 
`DEBUG_BUILD_CREDS=true fab dev deploy`

Output:
```bash
Traceback (most recent call last):
  File "~/myEnvironment/lib/python2.7/site-packages/fabric/main.py", line 757, in main
    *args, **kwargs
  File "~/myEnvironment/lib/python2.7/site-packages/fabric/tasks.py", line 386, in execute
    multiprocessing
  File "~/myEnvironment/lib/python2.7/site-packages/fabric/tasks.py", line 276, in _execute
    return task.run(*args, **kwargs)
  File "~/myEnvironment/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "~/myEnvironment/lib/python2.7/site-packages/boss/api/deployment/preset/web.py", line 87, in deploy
    buildman.build(stage, config)
  File "~/myEnvironment/lib/python2.7/site-packages/boss/api/deployment/buildman.py", line 411, in build
    runner.run_script(known_scripts.BUILD, remote=False)
  File "~/myEnvironment/lib/python2.7/site-packages/boss/api/runner.py", line 74, in run_script
    host_info(info_text, remote=remote)
  File "~/myEnvironment/lib/python2.7/site-packages/boss/util.py", line 25, in host_info
    host_print(green(msg), remote=remote)
  File "~/myEnvironment/lib/python2.7/site-packages/boss/util.py", line 20, in host_print
    _local(cmd)
  File "~/myEnvironment/lib/python2.7/site-packages/fabric/operations.py", line 1202, in local
    with_env = _prefix_env_vars(command, local=True)
  File "~/myEnvironment/lib/python2.7/site-packages/fabric/operations.py", line 712, in _prefix_env_vars
    for k, v in env_vars.iteritems()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 123: ordinal not in range(128)
Disconnecting from IP_ADDRESS... done.
```

System details:
```bash
boss: 1.0.0-alpha.19
Fabric: 1.13.2
Paramiko: 2.4.2
pip: 18.1
Python: 2.7.15
OS: Arch Linux
```

**Comment by kabirbaidhya** [comment]
Looks like this is a fabric specific issue, we can't fix this in boss. Closing.

**Comment by sanjeevkpandit** [comment]
@kabirbaidhya The issue disappeared after removing `oh-my-zsh`. Quiet different. :smile:
